install:
  - ps: choco install make

build_script:
  - cmake -DCMAKE_CXX_COMPILER=g++-6 CMakeLists.txt
  - make 
  - make test

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
